### ISSUE TITLE
IndexOutOfRangeException during C# compilation

### ISSUE THREAD

**Issue by harrison314** [badamczewski/PowerUp#10]
Hello,
i used PowerUpWatcher (commit 894ffa42ee58396acf55262bfaff9a7c8c1ebe9f) on Windows 11 64-bit.

With `test.cs`:
```cs
int M(int i)
{
    if(i==1) return 1;
    i++;
    i++;
    return i;
}
```

alwais write to `test.asm`:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PowerUp.Watcher.ILWriter.ToILString(DecompilationUnit unit) in C:\Users\**\Desktop\PowerUp-main\src\PowerUp.Watcher\ILWriter.cs:line 20
   at PowerUp.Watcher.CSharpWatcher.<>c__DisplayClass10_0.<<WatchFile>b__0>d.MoveNext() in C:\Users\**\Desktop\PowerUp-main\src\PowerUp.Watcher\CSharpWatcher.cs:line 218
```

I compile project using `dotnet publish -c Release -f net6.0`.

And screenshot of console output:
![obrázok](https://user-images.githubusercontent.com/12501763/166104985-8d0acd4e-35c1-4587-8219-a00b10045b58.png)

**Comment by badamczewski** [comment]
@harrison314 the Watcher is unable to find any file you provided (see the WARNING message in the log)  it will use you cmd working directory to figure out relative path, so either fix that or provide an aboslute path.
