### ISSUE TITLE
System.NotSupportedException exception on macOS

### ISSUE THREAD

**Issue by d0pare** [badamczewski/PowerUp#8]
Just wanted to let you know that watcher is writing the following exception into the output file when trying to run on macOS:

```
System.NotSupportedException: Passive attach is not supported on OSX.s
   at Microsoft.Diagnostics.Runtime.DataTarget.AttachToProcess(Int32 pid, UInt32 msecTimeout, AttachFlag attachFlag)
   at PowerUp.Core.Decompilation.JitCodeDecompiler.DecompileMethod(MethodInfo method, String functionCallName) in /Users/d0pare/Projects/GitHub/PowerUp/src/PowerUp.Core/Decompilation/JITDecompiler.cs:line 275
   at PowerUp.Core.Decompilation.JitExtensions.ToAsm(MethodInfo methodInfo, ILMethodMap[] sourceCodeMap) in /Users/d0pare/Projects/GitHub/PowerUp/src/PowerUp.Core/Decompilation/JITExtensions.cs:line 217
   at PowerUp.Core.Decompilation.JitExtensions.ToAsm(Type typeInfo, ILMethodMap[] sourceCodeMap, Boolean private) in /Users/d0pare/Projects/GitHub/PowerUp/src/PowerUp.Core/Decompilation/JITExtensions.cs:line 162
   at PowerUp.Watcher.CSharpWatcher.DecompileToASM(String code) in /Users/d0pare/Projects/GitHub/PowerUp/src/PowerUp.Watcher/CSharpWatcher.cs:line 612
   at PowerUp.Watcher.CSharpWatcher.<>c__DisplayClass10_0.<<WatchFile>b__0>d.MoveNext() in /Users/d0pare/Projects/GitHub/PowerUp/src/PowerUp.Watcher/CSharpWatcher.cs:line 178
```
Seems like the latest `clrmd` version of [DataTarget](https://github.com/microsoft/clrmd/blob/master/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs#L416-L419) is supporting macOS but with slightly modified API compared to the current [one](https://github.com/microsoft/clrmd/blob/release/1.1/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DataTarget.cs#L148-L151).

**Comment by badamczewski** [comment]
Thanks, it makes it hard for me to fix this issue since I don't have access to a Mac at the moment, but I'll see what I can do.

**Comment by badamczewski** [comment]
I have upgraded ClrMD to v2.0 so this should work now? Can you check?

**Comment by d0pare** [comment]
It works! Thank you very much.
